//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prodyktEntities : DbContext
    {
        public prodyktEntities()
            : base("name=prodyktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static prodyktEntities _context;
        public static prodyktEntities GetContext()
        {
            if (_context == null)
            {
                _context = new prodyktEntities();
            }
            return _context;
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<инсталляция> инсталляция { get; set; }
        public virtual DbSet<пользователь> пользователь { get; set; }
        public virtual DbSet<прикладная_область> прикладная_область { get; set; }
        public virtual DbSet<программный_продукт> программный_продукт { get; set; }
    }
}
