//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class инсталляция
    {
        public string код_пользователя { get; set; }
        public int код_продукта { get; set; }
        public decimal стоимость_инсталляции { get; set; }
        public System.DateTime дата_инсталляции { get; set; }
        public System.DateTime дата_деинсталляции { get; set; }
        public int кол_во_лицензий { get; set; }
    
        public virtual пользователь пользователь { get; set; }
        public virtual программный_продукт программный_продукт { get; set; }
    }
}
