//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class программный_продукт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public программный_продукт()
        {
            this.инсталляция = new HashSet<инсталляция>();
        }
    
        public int код_продукта { get; set; }
        public string название_продукта { get; set; }
        public string версия { get; set; }
        public System.DateTime дата_выпуска { get; set; }
        public string код_прикл_области { get; set; }
        public Nullable<decimal> стоимость_лицензии { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<инсталляция> инсталляция { get; set; }
        public virtual прикладная_область прикладная_область { get; set; }
    }
}
